### ISSUE TITLE
семантика

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-10-Figma#1]
https://github.com/BohdanLuts/home-work-lesson-10-Figma/blob/28e6df148df0536005e74c947aa882d0f99a5613/index.html#L68
- це схоже на заголовки 3-го рівня

https://github.com/BohdanLuts/home-work-lesson-10-Figma/blob/28e6df148df0536005e74c947aa882d0f99a5613/index.html#L179
- це схоже на списки

**Comment by BohdanLuts** [comment]
Змінено.
