### ISSUE TITLE
Перехід до вузького вьюпорта

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-10-Figma#2]
https://github.com/BohdanLuts/home-work-lesson-10-Figma/blob/28e6df148df0536005e74c947aa882d0f99a5613/css/style.css#L329
- для більш плавної адаптації можна додавати більше брекпойнтів і, нарпиклад, секцію Make your work easier переносити поступово: 2 рядки по 3 блока, 3 рядки по 2 блока, 5 рядків по 1 блоку.

**Comment by BohdanLuts** [comment]
Виправив переповнення по горизонталі по рекомендації. Викликано воно було величезним фоновим елліпсом.
Прописано брейкпоінти.
